### ISSUE TITLE
What coordinate system is the decoded position information belong to?

### ISSUE THREAD

**Issue by Charky-Chou** [muccc/iridium-toolkit#101]
really thanks to your code, but i have a question now:
after bit_parser ,we can get the position information about Satellite or spot beam position. (it's self.ra_pos_x , self.ra_pos_y , self.ra_pos_z in bitsparser.py , at line 1487), but i have no idea what coordinate system the information belong to . could you tell me ?
thank U!

**Comment by Sec42** [comment]
The coordinate system used is called ECEF (see https://en.wikipedia.org/wiki/Earth-centered,_Earth-fixed_coordinate_system )
Check for example [beam-reception-plotter.py](https://github.com/muccc/iridium-toolkit/blob/master/beam-reception-plotter.py) which contains coordinate conversion code
