### ISSUE TITLE
IndexError: string index out of range

### ISSUE THREAD

**Issue by Guillaume-JEAN** [muccc/iridium-toolkit#104]
Hi !
i am using gr-iridium and iridium-toolkit for long acquisition (i have made a script that run gr-iridium, save the output, read it and parse it using iridium-parser.py) and sometimes i get this error, which stop the acquisition :

Traceback (most recent call last):
File " .../gnuradio/gr-iridium/iridium-toolkit/iridium-parser.py", line 1606, in <module>
do_input(input)
File "…/gnuradio/gr-iridium/iridium-toolkit/iridium-parser.py", line 1520, in do_input
perline(Message(line.strip()).upgrade())
File "… /gnuradio/gr-iridium/iridium-toolkit/iridium-parser.py", line 247, in upgrade
access.append(map[int(self.bitstream_raw[x+0])*2 + int(self.bitstream_raw[x+1])])
IndexError: string index out of range

this error may appear after 10 min as well as after an hour or not at all.
Do you know what might cause this ? and is there a way to prevent it ?

Thank in advance for your response and for this great toolkit !

**Comment by Sec42** [comment]
Hi,

based on the error message you pasted, you are using a iridium-parser version that is at least 1.5 years old. This code line itself does not exist anymore. Can you try with a more current version? (master from git should work fine)

**Comment by Guillaume-JEAN** [comment]
It took me longer than expected to update everything, but this seems to have solved the problem!

Thank you very much

**Comment by Sec42** [comment]
Great to hear. Have fun!
