### ISSUE TITLE
play-iridium-ambe: not found

### ISSUE THREAD

**Issue by Lunny1993** [muccc/iridium-toolkit#106]
play-iridium-ambe: not found

![2023-09-08-041144_1920x1080_scrot](https://github.com/muccc/iridium-toolkit/assets/45454215/cf13fb73-49e6-4cb8-9e52-9b5e0e17c995)
![2023-09-08-041212_1920x1080_scrot](https://github.com/muccc/iridium-toolkit/assets/45454215/42140286-f43f-4c32-a870-ee1b18f16de0)

What do I need to do to fix this？

**Comment by RyokoAsakura** [comment]
I believe you have to put your iridium toolkit folder in your PATH.

**Comment by Sec42** [comment]
correct
