### ISSUE TITLE
Legacy extractor question

### ISSUE THREAD

**Issue by mebrown47** [muccc/iridium-toolkit#107]
Experimenting with the legacy code contained in /extractor-python. What version python and numpy were used? I'm using conda to create a compatible environment. Thanks

**Comment by Sec42** [comment]
Hi,

On Thu, Dec 28, 2023 at 14:33 -0800, ElbaSatGuy wrote:
> Experimenting with the legacy code contained in /extractor-python.
> What version python and numpy were used? I'm using conda to create a
> compatible environment. Thanks

It was all python 2.7. I don't remember more details at the moment. Let
me kowif you can get it to work.

CU,
    Sec
-- 
When in doubt, invent a chinese proverb.
