### ISSUE TITLE
Error while running update-tracking

### ISSUE THREAD

**Issue by alphapats** [muccc/iridium-toolkit#108]
Error while running update-tracking, path 'http://www.celestrak.com/NORAD/elements/iridium.txt' give no response and has been moved. Required to be updated.

![image](https://github.com/muccc/iridium-toolkit/assets/20792136/28ad4d94-66c6-4eb1-988a-c31abbda4f74)

./update-tracking 

--2024-02-21 15:23:50--  http://www.celestrak.com/NORAD/elements/iridium.txt
Resolving www.celestrak.com (www.celestrak.com)... 104.168.149.178
Connecting to www.celestrak.com (www.celestrak.com)|104.168.149.178|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://celestrak.org/NORAD/elements/iridium.txt [following]
--2024-02-21 15:23:51--  http://celestrak.org/NORAD/elements/iridium.txt
Resolving celestrak.org (celestrak.org)... 104.168.149.178
Reusing existing connection to www.celestrak.com:80.
HTTP request sent, awaiting response... 404 Not Found
2024-02-21 15:23:52 ERROR 404: Not Found.

cp: cannot stat 'iridium.txt': No such file or directory
--2024-02-21 15:23:52--  http://www.celestrak.com/NORAD/elements/iridium-NEXT.txt
Resolving www.celestrak.com (www.celestrak.com)... 104.168.149.178
Connecting to www.celestrak.com (www.celestrak.com)|104.168.149.178|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://celestrak.org/NORAD/elements/iridium-NEXT.txt [following]
--2024-02-21 15:23:52--  http://celestrak.org/NORAD/elements/iridium-NEXT.txt
Resolving celestrak.org (celestrak.org)... 104.168.149.178
Reusing existing connection to www.celestrak.com:80.
HTTP request sent, awaiting response... 404 Not Found
2024-02-21 15:23:53 ERROR 404: Not Found.

![Uploading Screenshot from 2024-02-21 15-27-42.png…]()

**Comment by Sec42** [comment]
You're right. I forgot to push the corresponding change out. Should be ok again now :-)
