### ISSUE TITLE
Link to TNT AMBE not working

### ISSUE THREAD

**Issue by dsound** [muccc/iridium-toolkit#13]
When I try to 'git clone' into the first link, it says 'can't find location'. It seems that the link takes us to a page on Osmocom that has files but no way to get them.

**Comment by gyaresu** [comment]
`$ git clone http://git.osmocom.org/osmo-ir77/`
`cd osmo-ir77/codec`

**Comment by schneider42** [comment]
Readme has been updated. Thanks.
