### ISSUE TITLE
Reading output.bits file in Wireshark?

### ISSUE THREAD

**Issue by schneider42** [muccc/iridium-toolkit#16]
Original issue: https://github.com/muccc/gr-iridium/issues/9

How does one prepare the raw output.bits file for Wireshark? I've had success with voice but wondering about sms as demonstrated in the CCC video?

**Comment by Sec42** [comment]
Published in commit 57587570e7c24ad5e27d7a3aa3eb9478816d3e70 see also the bottom of the current README.md
