### ISSUE TITLE
Iridium link #3 idea

### ISSUE THREAD

**Issue by ian2000611** [muccc/iridium-toolkit#17]
In your presentation at The Eleventh Hope you mentioned that it was 6 bit frames with a checksum. Have you tried running the data through a base64 decoder?

**Comment by Sec42** [comment]
A base64 decoder decodes data that has been encoded in an 8-bit transport stream. The data in question looks like a 6-bit transport stream, so this isn't applicable here.

**Comment by vaisala** [comment]
Xlink formats including 6-bit is detailed here: 
http://www.sutron.com/documents/xlink-manual-3.pdf
