### ISSUE TITLE
Track KML altitudeMode is set in the wrong place

### ISSUE THREAD

**Issue by mrjacobagilbert** [muccc/iridium-toolkit#27]
The line setting  altitudeMode for KML tracks here https://github.com/muccc/iridium-toolkit/blob/master/mkkml#L262 should actually be within <gx:Track> and moved before Line 265. As-is, google earth will load the tracks with altitudeMode clampToGround (default).

I am not an expert in KML, just implementing the fix from [the google group here](https://groups.google.com/forum/#!topic/cesium-dev/GX3IC0Ee9ag); it is possible it must to be in both locations but at least for Google Earth it loads correctly with it set only within <gx:Track>.

I'll submit a PR when I get a chance; for now I wanted to document this.

**Comment by Sec42** [comment]
thanks for the report.
