### ISSUE TITLE
iridium-parser.py errors in latest update.

### ISSUE THREAD

**Issue by Oojimentis** [muccc/iridium-toolkit#30]
Hi,
Having problems with the new parser. Seems to be adding decimal numbers that are messing up the reassembler and stats-voc programs.

Here's a comparison of the parsed output from the old and new versions:

OUTPUT.PARSED - Old version:

IDA: i-1595724308-t1 000000844 1624457600  97%   0.000 179 DL LCW(2,T:maint,C:sync[status:1,dtoa:1022,dfoa:255](0),786175 E0)                                                 000 cont=0 0 ctr=000 000 len=00 0:0000 [87.3a.09.b7.30.a7.d8.0b.79.d0.c2.f2.35.fc.00.6f.c0.07.fc.00.00.00.00]  ---    0000
IBC: i-1595724308-t1 000000846 1624540928  96%   0.000 136 DL bc:0 sat:02 cell:28 0 ts:1 sv_blkn:0 aq_cl:1111111111111111 aq_sb:26 aq_ch:2 00 0000 time:2020-07-26T00:45:11Z 101 11110101 ts:2 ul_sb:02 dl_sb:00 000 dtoa:000 dfoa:00 00

OUTPUT.PARSED - New version: note the  000000844**.000**

IDA: i-1595724308-t1 000000844.000 1624457600  97%   0.000 179 DL LCW(2,T:maint,C:sync[status:1,dtoa:1022,dfoa:255],0|0 E0)                                                       000 cont=0 0 ctr=000 000 len=00 0:0000 [87.3a.09.b7.30.a7.d8.0b.79.d0.c2.f2.35.fc.00.6f.c0.07.fc.00.00.00.00]  ---    0000
IBC: i-1595724308-t1 000000846.000 1624540928  96%   0.000 136 DL bc:0 sat:002 cell:28 0 slot:1 sv_blkn:0 aq_cl:1111111111111111 aq_sb:26 aq_ch:2 00 0000 time:2020-07-26T00:45:11.65Z 101 Rid:245 ts:3 ul_sb:02 dl_sb:00 access:1 dtoa:000 dfoa:00 00 descr_extra:0000011001

Running stats-voc gives:

~/Dev/iridium-toolkit$ python stats-voc.py output.parsed
Traceback (most recent call last):
  File "stats-voc.py", line 97, in <module>
    main()
  File "stats-voc.py", line 76, in main
    tsl, fl, quals, _ = filter_voc()
  File "stats-voc.py", line 27, in filter_voc
    ts = ts_base + int(line_split[2])/1000.
ValueError: invalid literal for int() with base 10: '000001105.000'

Re assembler gives:

sudo ./reassembler.py -i output.parsed -m msg
Couldn't parse input line:  IDA: i-1595724308-t1 000000844.000 1624457600  97%   0.000 179 DL LCW(2,T:maint,C:sync[status:1,dtoa:1022,dfoa:255],0|0 E0)                                                       000 cont=0 0 ctr=000 000 len=00 0:0000 [87.3a.09.b7.30.a7.d8.0b.79.d0.c2.f2.35.fc.00.6f.c0.07.fc.00.00.00.00]  ---    0000

I'm running:

Description:	Ubuntu 18.04.4 LTS

~/Dev/iridium-toolkit$ python
Python 2.7.17 (default, Jul 20 2020, 15:37:01) 
[GCC 7.5.0] on linux2

Thanks!!

**Comment by Sec42** [comment]
Some tools were not ready to deal with the more precise timestamps that iridium-extractor now outputs.

Should be fixed with dc8a5f3
