### ISSUE TITLE
NameError: global name 'uwec' is not defined

### ISSUE THREAD

**Issue by Geezerjem** [muccc/iridium-toolkit#32]
On a new install I have just made, I got 'NameError: global name 'uwec' is not defined' when running iridium-parser.py . The full message is 

jem@jem-Big-One:~/Dev/iridium-toolkit$ python iridium-parser.py output20.bits > output20.parsed
Traceback (most recent call last):
  File "iridium-parser.py", line 1606, in <module>
    do_input(input)
  File "iridium-parser.py", line 1520, in do_input
    perline(Message(line.strip()).upgrade())
  File "iridium-parser.py", line 1589, in perline
    print(q.pretty()+" ERR:"+", ".join(q.error_msg))
  File "iridium-parser.py", line 302, in pretty
    str= "RAW: "+self._pretty_header()
  File "iridium-parser.py", line 275, in _pretty_header
    if uwec:
NameError: global name 'uwec' is not defined

I had to add
uwec = False
to the declarations that start at line 56 to fix it. 
I guess whatever the previous version of Python I had just magically ignored it was missing ... I've been using it for weeks on the previous install.

Cheers,

Jem.

**Comment by Sec42** [comment]
This was part of a local change, mistakenly commited in affbfda. I've now pushed the second part of this change as c6cd85a so it should be fixed.
