### ISSUE TITLE
reassembler.py No Attribute 'signal'

### ISSUE THREAD

**Issue by notpike** [muccc/iridium-toolkit#36]
Hi,

Running into an issue with reassembler.py where I'm getting an... 
`AttributeError: 'MyObject' object has no attribute 'signal'`
on line 114. I didn't see any other references for signal in the MyObject class or in reassembler.py so I'm not quite sure where this value is being pulled from.  

Thanks!

**Comment by skipak** [comment]
Which mode is the error on?  Others besides sbd?

**Comment by notpike** [comment]
> Which mode is the error on? Others besides sbd?

msg and sbd.

Thank you.

**Comment by Sec42** [comment]
Sorry, was a small bug on my end. Pushed a fix just now. Let me know if it works again for you now.

**Comment by notpike** [comment]
No worries and thank you for maintaining this code! :D

**Comment by notpike** [comment]
OK!
Tested it and it was successful. Thanks again for your help!
