### ISSUE TITLE
dtoa & dfoa

### ISSUE THREAD

**Issue by tianyasy** [muccc/iridium-toolkit#41]
in the bch downlink assignment and lcw messages,  what's the unit of dtoa/dfoa/f_dtoa/f_dfoa, is that dtoa in milliseconds or something other? and is that dfoa in Hz or others? but at the same time, the doppler frequency would be negative or positive.

thanks

**Comment by Sec42** [comment]
Hi,

The decoding and names of these fields have been obtained from reverse engineering the debug mode of the 9601 modem. This means, that unfortunately we have no further info about the meaning of these fields. If you figure something out, let us know.

CU,
    Sec
