### ISSUE TITLE
"sh:1:play-iridium-ambe: not found" error, but play-iridium-ambe file was already in the path

### ISSUE THREAD

**Issue by BH6AZP** [muccc/iridium-toolkit#42]
I met this issue when I use stat-voc.py, my os is DragonOS. Here is some terminal information.
![捕获](https://user-images.githubusercontent.com/89366604/149086267-68d92884-b445-48b0-8e0c-9f8c49f08c91.PNG)

**Comment by Sec42** [comment]
You show play-iridium-ambe in the same directory, but you do not show your $PATH.

I suspect your path does not contain the "/usr/src/iridium-toolkit" directory.

Can you try adding it to your PATH by typing
 
```
PATH=${PATH}:/usr/src/iridium-toolkit
```
in the shell before you run stats-voc?

**Comment by Sec42** [comment]
@BH6AZP Any update on this? Otherwise I'm going to close this issue
