### ISSUE TITLE
ValueError: math domain error

### ISSUE THREAD

**Issue by amitpathania** [muccc/iridium-toolkit#44]
When I am trying to parse output.bits using iridium-parser.py, I am getting following error after few frames.
`Traceback (most recent call last):
  File "iridium-parser.py", line 1774, in <module>
    do_input(input)
  File "iridium-parser.py", line 1691, in do_input
    perline(Message(line.strip()).upgrade())
  File "iridium-parser.py", line 228, in __init__
    self.leveldb=20*log(self.level,10)
ValueError: math domain error

`
Anyone else also facing the same problem??

**Comment by Sec42** [comment]
This likely means the signal level for that packet in the bits file was 0. We seem to output it to 5 digits of precision in gr-iridium which means that your signal level was smaller than -100dBFS

Which kind of SDR are you using that can receive such low signals?

Nonetheless, I'll push a workaround in a bit so the parser doesn't die on these lines.
