### ISSUE TITLE
Live decoding?

### ISSUE THREAD

**Issue by thebaldgeek** [muccc/iridium-toolkit#47]
I'd like to get a live stream of sbd messages into Node-RED via a UDP stream.
To try and achieve this, here is what I am testing:    
```iridium-extractor -D 4 rtl-sdr.conf | iridium-parser.py -p | reassember.py -m sbd | udp-for-il.py```
I see good %, from the extractor but no messages.    
Am I on the right track to pipe each application like that?
If not, how can I get the 3 programs to work in a chain?

Thanks.

**Comment by Sec42** [comment]
This is more of a python/unix question & not really related to the iridium-toolkit.

Most programs on unix behave specially when their output is a terminal - Terminal output is usually "line buffered" i.e. the output is flushed/printed at each newline. Whereas for pipes you have the some (larger) standard buffer. On Linux it is about 64k bytes these days, i think.

So while piping there needs to be a larger amount of output before it is "flushed" and sent to the next program.

So your pipe should work as it is, but will only send output to `udp-for-il.py` in larger batches, which may - depending on the amount of traffic you see - take quite some time.

Different programs on unix have command line options to address this issue. For example for `grep` it is:

       --line-buffered
              Use line buffering on output.  This can cause a performance penalty.

For python one can use the `-u` option as shown in `man python`:

       -u     Force the stdout and stderr streams to be unbuffered.  This option has no effect on the stdin stream.

so your pipe would need to look like `.... | python -u reassember.py -m sbd | udp-for-il.py`

Technically, the same issue happens with `iridium-parser.py` in your pipeline, but as that one produces far more output, it is less noticable.
