### ISSUE TITLE
ModuleNotFoundError: No module named 'crcmod'

### ISSUE THREAD

**Issue by AdmiralGeta** [muccc/iridium-toolkit#48]
Hi, I try to run new "acars" mode but I get error ModuleNotFoundError: No module named 'crcmod', I check all folder but this module 'crcmod' does not exist, where can i get this module

**Comment by Sec42** [comment]
Hi,

as stated in the README, crcmod is a requisite. You need to install it. It depends on your OS on how to do that. On ubuntu `apt-get install python3-crcmod` might work. As it is a python module, `pip3 install crcmod` might also do the trick.
