### ISSUE TITLE
Get IRA packets

### ISSUE THREAD

**Issue by zhusiyu6** [muccc/iridium-toolkit#85]
How long is the launch cycle of iridium's IRA packets? Why can I only receive IMS packets for a long time

**Comment by Sec42** [comment]
Each spot beam sends an IRA every 43.2 seconds. Total amount varies depending on how many satellites and spot beams you see at the same time and may be multiple per second.

IMS are sent with a higher signal strength. If you only see those, your setup is likely not sensitive enough.

**Comment by zhusiyu6** [comment]
I use gr-iridium to receive iridium frames. How can I adjust it?

**Comment by zhusiyu6** [comment]
It has been solved，thank you

> I use gr-iridium to receive iridium frames. How can I adjust it?

It has been solved,thank you
