### ISSUE TITLE
tracking satellites

### ISSUE THREAD

**Issue by graememilne** [muccc/iridium-toolkit#94]
In the tracking folder ,update-tracking is still using iridium.txt as well as iridium-NEXT.txt.
My understanding is the iridium sats numbered <100 are decommissioned.
But still show up on the iridium-live map.
Also hardly any of the iridium-NEXT sats show up numbered >100.

These are pre-installed on the Dragon os-focal R26

**Comment by Sec42** [comment]
Iridium-internal satellite numbering (IRA) unfortunately does not match the "official" NORAD names.
If you're interested in more details & how to generate a mapping: check Issue https://github.com/muccc/iridium-toolkit/issues/28
