### ISSUE TITLE
ambe codec not found 

### ISSUE THREAD

**Issue by rustjakey** [muccc/iridium-toolkit#99]
Same issue as this closed post [](https://github.com/muccc/iridium-toolkit/issues/42)

Have tried the suggested solution but no luck.

Any help greatly appreciated. 

![image](https://user-images.githubusercontent.com/79246335/222536598-822d183d-1638-4065-a9b2-32ad44412c18.png)

![image](https://user-images.githubusercontent.com/79246335/222536705-c1a38cb2-b1ad-4eb6-ba14-6ef99ae13852.png)

**Comment by schneider42** [comment]
try "export PATH=`...

**Comment by rustjakey** [comment]
After doing that, the terminal session cant start py. 

If I start a new terminal, the PATH changes are reset but I am back at square one. 

Thanks

![image](https://user-images.githubusercontent.com/79246335/224404555-a6e46d90-6c41-4b7e-bced-e33c523b83ad.png)

**Comment by rustjakey** [comment]
Seem to have fixed that issue with `export PATH="/usr/bin:$PATH"`

**Comment by rustjakey** [comment]
Worked once. This is the path now
![image](https://user-images.githubusercontent.com/79246335/224408548-3e60f2e4-f6f7-4bef-9746-eb4138a681a8.png)

**Comment by rustjakey** [comment]
I cleared all the changes I made to the env variable files and put it in the bashrc one. Works. Now another Issue I will open separately.
